"use client";

import { useState, useCallback, useRef } from "react";
import dynamic from "next/dynamic";
import { motion, AnimatePresence } from "framer-motion";
import { StatsGrid } from "@/components/dashboard/stats-grid";
import { RiskGauge } from "@/components/dashboard/risk-gauge";
import { AIInsightCard } from "@/components/dashboard/ai-insight-card";
import { LiveActivityFeed } from "@/components/dashboard/live-activity-feed";
import { DistrictDetailDrawer } from "@/components/dashboard/district-detail-drawer";
import { useToast } from "@/components/shared/toast-provider";
import { aiInsights, aiRecommendations, predictiveTimeline } from "@/data/synthetic/analytics";
import { Brain, Heart, AlertTriangle, Zap, TrendingUp, Clock, Shield, Download, FileText, FileSpreadsheet, CheckCircle2, Loader2 } from "lucide-react";
import Link from "next/link";

const HungerTrendChart = dynamic(
  () => import("@/components/charts/hunger-trend-chart").then((m) => m.HungerTrendChart),
  { ssr: false, loading: () => <div className="warm-card h-[340px] shimmer" /> }
);

const FoodInflationChart = dynamic(
  () => import("@/components/charts/food-inflation-chart").then((m) => m.FoodInflationChart),
  { ssr: false, loading: () => <div className="warm-card h-[340px] shimmer" /> }
);

const RiskDistributionChart = dynamic(
  () => import("@/components/charts/risk-distribution-chart").then((m) => m.RiskDistributionChart),
  { ssr: false, loading: () => <div className="warm-card h-[340px] shimmer" /> }
);

const HungerHeatmap = dynamic(
  () => import("@/components/maps/hunger-heatmap").then((m) => m.HungerHeatmap),
  { ssr: false, loading: () => <div className="warm-card h-[350px] shimmer" /> }
);

/* ─── AI Analysis processing stages ─── */
const AI_STAGES = [
  "Connecting to data sources…",
  "Analyzing attendance patterns…",
  "Processing food price indices…",
  "Running risk prediction models…",
  "Generating district projections…",
  "Correlating intervention outcomes…",
  "Compiling intelligence report…",
  "Finalizing analysis…",
] as const;

export default function DashboardPage() {
  const [drawerDistrictId, setDrawerDistrictId] = useState<string | null>(null);
  const [exportOpen, setExportOpen] = useState(false);
  const [aiRunning, setAiRunning] = useState(false);
  const [aiStage, setAiStage] = useState(0);
  const [aiProgress, setAiProgress] = useState(0);
  const [refreshKey, setRefreshKey] = useState(0);
  const [lastUpdated, setLastUpdated] = useState("5 min ago");
  const exportRef = useRef<HTMLDivElement>(null);
  const { showToast } = useToast();

  /* ─── Export Report handler ─── */
  const handleExport = useCallback((format: "pdf" | "csv" | "txt") => {
    setExportOpen(false);

    const now = new Date();
    const timestamp = now.toISOString().replace(/[:.]/g, "-").slice(0, 19);
    const filename = `asha-intelligence-report-${timestamp}.${format}`;

    let content: string;
    let mimeType: string;

    if (format === "csv") {
      content = "District,Risk Score,Risk Level,Trend,Attendance,Meal Participation,Projected 7d,Projected 30d\n";
      content += "Shravasti,82,critical,worsening,58.7,49.3,89,95\n";
      content += "Anantapur,78,high,worsening,62.5,54.8,84,88\n";
      content += "Koraput,74,high,stable,64.1,57.2,79,82\n";
      content += "Kalahandi,72,high,stable,66.3,60.1,81,79\n";
      content += "Nandurbar,68,moderate,improving,72.8,63.4,64,59\n";
      content += "Dakshin Dinajpur,62,moderate,stable,70.2,65.5,66,63\n";
      content += "Jaisalmer,55,moderate,improving,74.6,68.9,51,47\n";
      content += "Ernakulam,28,low,improving,89.4,87.2,24,20\n";
      mimeType = "text/csv";
    } else if (format === "txt") {
      content = `ASHA INTELLIGENCE — DASHBOARD REPORT\n`;
      content += `Generated: ${now.toLocaleString()}\n`;
      content += `${"=".repeat(50)}\n\n`;
      content += `NATIONAL RISK SCORE: 65.8 / 100\n`;
      content += `DISTRICTS MONITORED: 8\n`;
      content += `CRITICAL ALERTS: 3\n`;
      content += `AI CONFIDENCE: 89%\n\n`;
      content += `CRITICAL DISTRICTS:\n`;
      content += `  • Shravasti — Risk: 82 (↑ worsening)\n`;
      content += `  • Anantapur — Risk: 78 (↑ worsening)\n`;
      content += `  • Koraput   — Risk: 74 (→ stable)\n`;
      content += `  • Kalahandi — Risk: 72 (→ stable)\n\n`;
      content += `AI INSIGHTS ACTIVE: ${aiInsights.length}\n`;
      content += `RECOMMENDATIONS PENDING: ${aiRecommendations.length}\n\n`;
      content += `Report generated by Asha Intelligence AI Engine v2.1\n`;
      mimeType = "text/plain";
    } else {
      // PDF simulation — generate a rich text file
      content = `%PDF-SIMULATION\n\nAsha Intelligence — National Dashboard Report\n`;
      content += `Generated: ${now.toLocaleString()}\n\n`;
      content += `This is a simulated PDF export. In production, this would generate\n`;
      content += `a formatted PDF with charts, maps, and detailed analytics.\n\n`;
      content += `National Risk Score: 65.8\n`;
      content += `Districts: 8 | Critical: 2 | High: 2 | Moderate: 3 | Low: 1\n`;
      mimeType = "application/octet-stream";
    }

    // Trigger browser download
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    showToast(`${format.toUpperCase()} exported successfully — ${filename}`, "success");
  }, [showToast]);

  /* ─── Run AI Analysis handler ─── */
  const handleRunAI = useCallback(() => {
    if (aiRunning) return;
    setAiRunning(true);
    setAiStage(0);
    setAiProgress(0);

    const totalDuration = 4000; // 4 seconds total
    const stageInterval = totalDuration / AI_STAGES.length;
    const progressInterval = 50; // update progress every 50ms
    const progressIncrement = 100 / (totalDuration / progressInterval);

    // Progress bar
    const progressTimer = setInterval(() => {
      setAiProgress((prev) => {
        const next = prev + progressIncrement;
        return next >= 100 ? 100 : next;
      });
    }, progressInterval);

    // Stage text
    const stageTimer = setInterval(() => {
      setAiStage((prev) => {
        const next = prev + 1;
        return next >= AI_STAGES.length ? AI_STAGES.length - 1 : next;
      });
    }, stageInterval);

    // Completion
    setTimeout(() => {
      clearInterval(progressTimer);
      clearInterval(stageTimer);
      setAiProgress(100);
      setAiStage(AI_STAGES.length - 1);

      setTimeout(() => {
        setAiRunning(false);
        setRefreshKey((k) => k + 1); // trigger visual refresh
        setLastUpdated("Just now");
        showToast("AI analysis complete — dashboard updated with latest intelligence", "success");
      }, 400);
    }, totalDuration);
  }, [aiRunning, showToast]);

  /* ─── Close export on outside click ─── */
  const handleExportBlur = useCallback(() => {
    setTimeout(() => setExportOpen(false), 200);
  }, []);

  return (
    <div className="space-y-6 max-w-[1600px] mx-auto">
      {/* District Detail Drawer */}
      <DistrictDetailDrawer
        isOpen={drawerDistrictId !== null}
        onClose={() => setDrawerDistrictId(null)}
        districtId={drawerDistrictId}
      />

      {/* AI Analysis Overlay */}
      <AnimatePresence>
        {aiRunning && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[55] flex items-center justify-center bg-asha-ink/30 backdrop-blur-sm"
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="bg-white rounded-2xl shadow-2xl p-8 max-w-md w-full mx-4 border border-asha-glass-border"
            >
              <div className="flex items-center gap-3 mb-5">
                <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-asha-teal to-asha-emerald flex items-center justify-center">
                  <Brain className="w-5 h-5 text-white animate-pulse" />
                </div>
                <div>
                  <h3 className="text-base font-bold text-asha-ink">Running AI Analysis</h3>
                  <p className="text-[11px] text-asha-ink-lighter">Processing live intelligence data…</p>
                </div>
              </div>

              {/* Progress bar */}
              <div className="mb-3">
                <div className="h-2 bg-asha-cream-dark rounded-full overflow-hidden">
                  <motion.div
                    className="h-full rounded-full bg-gradient-to-r from-asha-teal to-asha-emerald"
                    animate={{ width: `${aiProgress}%` }}
                    transition={{ duration: 0.1 }}
                  />
                </div>
              </div>

              {/* Stage text */}
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Loader2 className="w-3.5 h-3.5 text-asha-teal animate-spin" />
                  <span className="text-xs text-asha-ink-light">{AI_STAGES[aiStage]}</span>
                </div>
                <span className="text-xs font-bold text-asha-teal tabular-nums">{Math.round(aiProgress)}%</span>
              </div>

              {/* Processing steps */}
              <div className="mt-4 space-y-1.5">
                {AI_STAGES.slice(0, aiStage + 1).map((stage, i) => (
                  <motion.div
                    key={stage}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    className="flex items-center gap-2"
                  >
                    {i < aiStage ? (
                      <CheckCircle2 className="w-3 h-3 text-asha-emerald flex-shrink-0" />
                    ) : (
                      <Loader2 className="w-3 h-3 text-asha-teal animate-spin flex-shrink-0" />
                    )}
                    <span className={`text-[11px] ${i < aiStage ? "text-asha-ink-lighter line-through" : "text-asha-ink"}`}>
                      {stage}
                    </span>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Page header */}
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex flex-col md:flex-row md:items-center justify-between gap-4"
      >
        <div>
          <h1 className="text-2xl font-bold text-asha-ink flex items-center gap-2">
            National Intelligence Dashboard
            <span className="inline-flex items-center gap-1 px-2 py-0.5 text-[10px] font-semibold bg-asha-teal-muted text-asha-teal-dark border border-asha-teal/15 rounded-full">
              <Heart className="w-3 h-3" /> LIVE
            </span>
          </h1>
          <p className="text-sm text-asha-ink-lighter mt-1">
            Real-time humanitarian intelligence across 8 districts • Last updated {lastUpdated}
          </p>
        </div>
        <div className="flex items-center gap-2">
          {/* Export Report — dropdown */}
          <div className="relative" ref={exportRef} onBlur={handleExportBlur}>
            <button
              onClick={() => setExportOpen((v) => !v)}
              className="px-4 py-2 text-xs font-medium rounded-xl bg-white border border-asha-glass-border text-asha-ink-light hover:bg-asha-cream-dark transition-colors flex items-center gap-1.5"
            >
              <Download className="w-3.5 h-3.5" />
              Export Report
            </button>
            <AnimatePresence>
              {exportOpen && (
                <motion.div
                  initial={{ opacity: 0, y: -5, scale: 0.95 }}
                  animate={{ opacity: 1, y: 0, scale: 1 }}
                  exit={{ opacity: 0, y: -5, scale: 0.95 }}
                  transition={{ duration: 0.15 }}
                  className="absolute right-0 top-full mt-1.5 w-48 bg-white rounded-xl shadow-lg border border-asha-glass-border overflow-hidden z-20"
                >
                  <button
                    onClick={() => handleExport("pdf")}
                    className="w-full flex items-center gap-3 px-4 py-2.5 text-xs text-asha-ink hover:bg-asha-cream transition-colors"
                  >
                    <FileText className="w-3.5 h-3.5 text-risk-critical" />
                    Export as PDF
                  </button>
                  <button
                    onClick={() => handleExport("csv")}
                    className="w-full flex items-center gap-3 px-4 py-2.5 text-xs text-asha-ink hover:bg-asha-cream transition-colors border-t border-asha-cream-dark/40"
                  >
                    <FileSpreadsheet className="w-3.5 h-3.5 text-asha-emerald" />
                    Export as CSV
                  </button>
                  <button
                    onClick={() => handleExport("txt")}
                    className="w-full flex items-center gap-3 px-4 py-2.5 text-xs text-asha-ink hover:bg-asha-cream transition-colors border-t border-asha-cream-dark/40"
                  >
                    <FileText className="w-3.5 h-3.5 text-asha-sky" />
                    Export as Text
                  </button>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* Run AI Analysis */}
          <button
            onClick={handleRunAI}
            disabled={aiRunning}
            className="px-4 py-2 text-xs font-medium rounded-xl bg-gradient-to-r from-asha-teal to-asha-emerald text-white hover:opacity-90 transition-opacity flex items-center gap-1.5 disabled:opacity-50"
          >
            {aiRunning ? (
              <>
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
                Analyzing…
              </>
            ) : (
              <>
                <Brain className="w-3.5 h-3.5" />
                Run AI Analysis
              </>
            )}
          </button>
        </div>
      </motion.div>

      {/* Stats grid */}
      <StatsGrid key={`stats-${refreshKey}`} />

      {/* Main content grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Heatmap - spans 2 cols */}
        <div className="lg:col-span-2">
          <HungerHeatmap compact />
        </div>

        {/* Risk gauge + critical districts + activity feed */}
        <div className="space-y-4">
          <RiskGauge score={65.8} />
          {/* Critical districts */}
          <div className="warm-card p-4">
            <div className="flex items-center gap-2 mb-3">
              <AlertTriangle className="w-4 h-4 text-asha-coral" />
              <h3 className="text-sm font-semibold text-asha-ink">Critical Districts</h3>
            </div>
            <div className="space-y-2">
              {[
                { id: "d3", name: "Shravasti", score: 82, trend: "↑", projected: 89 },
                { id: "d6", name: "Anantapur", score: 78, trend: "↑", projected: 84 },
                { id: "d4", name: "Koraput", score: 74, trend: "→", projected: 79 },
                { id: "d5", name: "Kalahandi", score: 72, trend: "→", projected: 81 },
              ].map((d, i) => (
                <motion.div
                  key={d.name}
                  initial={{ opacity: 0, x: 10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.5 + i * 0.1 }}
                  className="flex items-center justify-between py-2 px-3 rounded-xl bg-asha-cream hover:bg-asha-cream-dark transition-colors cursor-pointer"
                  onClick={() => setDrawerDistrictId(d.id)}
                >
                  <span className="text-xs font-medium text-asha-ink">{d.name}</span>
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-bold text-risk-critical">{d.score}</span>
                    <span className="text-[10px] text-asha-ink-lighter">→{d.projected}</span>
                    <span className="text-[10px] text-risk-critical">{d.trend}</span>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* AI Recommendations (V2) */}
      <div className="warm-card p-6">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <Zap className="w-5 h-5 text-asha-amber" />
            <h2 className="text-lg font-bold text-asha-ink">AI Intervention Recommendations</h2>
            <span className="px-2 py-0.5 text-[10px] font-semibold bg-asha-amber-muted text-asha-amber-dark border border-asha-amber/15 rounded-full">
              {aiRecommendations.length} active
            </span>
          </div>
          <Link href="/dashboard/interventions" className="text-xs font-medium text-asha-teal hover:text-asha-teal-dark transition-colors">
            View all →
          </Link>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {aiRecommendations.slice(0, 2).map((rec, i) => (
            <motion.div
              key={rec.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 + i * 0.15 }}
              className="p-4 rounded-xl bg-asha-cream border border-asha-glass-border hover:shadow-card transition-all"
            >
              <div className="flex items-center gap-2 mb-2">
                <span className={`px-2 py-0.5 text-[10px] font-bold uppercase rounded-full ${
                  rec.urgency === "immediate" ? "bg-risk-critical/10 text-risk-critical border border-risk-critical/20" :
                  rec.urgency === "urgent" ? "bg-risk-high/10 text-risk-high border border-risk-high/20" :
                  "bg-risk-moderate/10 text-risk-moderate border border-risk-moderate/20"
                }`}>
                  {rec.urgency}
                </span>
                <span className="text-[11px] text-asha-ink-lighter">{rec.districtName}</span>
              </div>
              <h4 className="text-sm font-semibold text-asha-ink mb-1">{rec.title}</h4>
              <p className="text-xs text-asha-ink-light line-clamp-2 mb-3">{rec.description}</p>
              <div className="flex items-center gap-4 text-[11px] text-asha-ink-lighter">
                <span className="flex items-center gap-1">
                  <Shield className="w-3 h-3" />
                  {rec.impactPrediction.childrenHelped.toLocaleString()} children
                </span>
                <span className="flex items-center gap-1">
                  <TrendingUp className="w-3 h-3" />
                  -{rec.impactPrediction.riskReduction}% risk
                </span>
                <span className="font-medium text-asha-teal">{(rec.confidence * 100).toFixed(0)}% conf.</span>
              </div>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Charts row */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <HungerTrendChart />
        <FoodInflationChart />
      </div>

      {/* Activity Feed + AI Insights + Risk Distribution */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Live Activity Feed (V2) */}
        <LiveActivityFeed />

        {/* AI Insights */}
        <div>
          <div className="flex items-center gap-2 mb-4">
            <Brain className="w-5 h-5 text-asha-violet" />
            <h2 className="text-sm font-bold text-asha-ink">AI Insights</h2>
            <span className="px-2 py-0.5 text-[10px] font-semibold bg-asha-violet-muted text-asha-violet border border-asha-violet/15 rounded-full">
              {aiInsights.length} active
            </span>
          </div>
          <div className="space-y-3">
            {aiInsights.slice(0, 4).map((insight, i) => (
              <AIInsightCard key={insight.id} insight={insight} index={i} />
            ))}
          </div>
        </div>

        {/* Risk distribution */}
        <div>
          <RiskDistributionChart />
        </div>
      </div>
    </div>
  );
}
